version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d portfolio"]
      interval: 3s
      retries: 5
      start_period: 30s
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend-network

  flask:
    build: flask
    restart: always
    env_file:
      - postgres.env
      - flask.env
    volumes:
      - ./flask:/flask
    ports:
      - 5000:5000
    networks:
      - backend-network
      - frontend-network
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: jonasal/nginx-certbot
    restart: unless-stopped
    env_file: 
      - nginx.env
    volumes:
      - nginx-secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend-network
    depends_on:
      - flask

volumes:
  postgres-data:
  nginx-secrets:
networks:
  backend-network:
  frontend-network:
